# Generated by Django 5.0.4 on 2024-04-13 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewPage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='current_fund',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='project',
            name='total_target',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Untitled Project', max_length=255),
        ),
    ]
