# Generated by Django 5.0.4 on 2024-04-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewPage', '0003_picture_project_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
